#!/bin/bash

# https://scottlinux.com/2013/08/30/block-geo-region-list-of-ips-with-ufw-in-linux/

ipRangeFile="filename"

while read line; do sudo ufw insert 1 deny from $line to any; done < $ipRangeFile
